version: '3.8'

services:
  api1:
    build: .
    expose:
      - "1730"
    volumes:
      - ./hospital.db:/app/hospital.db
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  api2:
    build: .
    expose:
      - "1730"
    volumes:
      - ./hospital.db:/app/hospital.db
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  api3:
    build: .
    expose:
      - "1730"
    volumes:
      - ./hospital.db:/app/hospital.db
      - ./uploads:/app/uploads
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - REACT_APP_API_URL=http://api1.turwin.tahabiyikli.com
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - api1
      - api2
      - api3
    restart: unless-stopped
